name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Папка для логів збірки

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Це дозволяє бачити історію комітів

      # 1. Встановлюємо Build Wrapper (обов'язково для C/C++)
      - name: Install Build Wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v3

      # 2. Збираємо проект (ЦЕ ГОЛОВНЕ, ЩО ТИ ПРОПУСТИВ)
      - name: Run Build Wrapper
        run: |
          # В цьому рядку заміни 'g++ *.cpp -o myapp' на твою команду компіляції!
          # Наприклад: make, або cmake --build ., або g++ main.c -o app
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} g++ *.cpp -o myapp

      # 3. Запускаємо аналіз
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Вказуємо шлях до звіту, який створив крок 2
          args: >
            -Dsonar.projectKey=RoshkoArtem_simple_math_lib
            -Dsonar.organization=roshkoartem
            -Dsonar.sources=.
            -Dsonar.cfamily.build-wrapper-output=${{ env.BUILD_WRAPPER_OUT_DIR }}
            -Dsonar.verbose=false
